// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyMPj1aqv6bxrr2AlZkP8NZ_QW5r5kE9M',
    appId: '1:371226462248:web:a4b7a46c577000b1c30d1d',
    messagingSenderId: '371226462248',
    projectId: 'ecommerce1flutter-ae9dc',
    authDomain: 'ecommerce1flutter-ae9dc.firebaseapp.com',
    storageBucket: 'ecommerce1flutter-ae9dc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJXMLUFbXhz4kE5QKV3I8OsL3vxPhlhv4',
    appId: '1:371226462248:android:9948cb8a2ef95542c30d1d',
    messagingSenderId: '371226462248',
    projectId: 'ecommerce1flutter-ae9dc',
    storageBucket: 'ecommerce1flutter-ae9dc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4C9wNFGStNkYUj9XCuLBTWCcHFH8yB8A',
    appId: '1:371226462248:ios:7f0268c6af202e58c30d1d',
    messagingSenderId: '371226462248',
    projectId: 'ecommerce1flutter-ae9dc',
    storageBucket: 'ecommerce1flutter-ae9dc.appspot.com',
    iosBundleId: 'com.example.flutterApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4C9wNFGStNkYUj9XCuLBTWCcHFH8yB8A',
    appId: '1:371226462248:ios:13b134a0e6645302c30d1d',
    messagingSenderId: '371226462248',
    projectId: 'ecommerce1flutter-ae9dc',
    storageBucket: 'ecommerce1flutter-ae9dc.appspot.com',
    iosBundleId: 'com.example.flutterApplication.RunnerTests',
  );
}
